### PR TITLE
Use prefixes less often

### PR DESCRIPTION
**Pull request by skronstein**
Changes siText.c so that the prefixes for large numbers (k, M, etc) are only used for numbers over 10000.
For example, after setting the resolution to 1280x1024, the FPS will show as "1057.362" FPS  instead of "1.057 36 k" fps on the record settings window, and "1057.4 fps" on the main window.

### CODE REVIEW

**Comment by oskirby** [comment]
There are a couple issues I see in this patch. The SI prefixes aren't applied consistently between the main window, and the record settings window, and it only applies to the kilo prefix. Seeing as how this only appears to make a difference on framerate, and that our camera is limited to at most 38000fps, I'd rather just drop the SI prefixes entirely when displaying framerate.

Although it's purely theoretical for now, this is also quite inconsistent for larger SI prefixes. For example we would still wind up displaying 1.057 Mfps if our camera magically got 1000x faster. A more general approach would be to try to prefer a display range for the mantissa portion of your number (ie: 10-10000), and then choose the SI prefix that matches this.

**Comment by DDR0** [comment]
Testing on Master, I can't edit the framerate FPS in the recording settings window. Rather, I can, but it doesn't do anything.

**Comment by DDR0** [comment]
Hm, not that it works on master either. Did it *ever* work? :confused:

**Comment by skronstein** [comment]
It actually does work.  One just has to press the enter key to apply changes.  I think the text for that key should be changed to "Apply".  Should I start a new branch for minor UI changes such as this?  They don't belong in this branch.

**Comment by DDR0** [comment]
Merged into master. :heavy_check_mark:

**Pull request closed without merging**
